telemetry = false
logLevel = "debug" # "debug" | "warn" | "error"

[console]
depth = 2

[install]
auto = "auto"
exact = true
optional = false
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200
# These packages will bypass the 3-day minimum age requirement
minimumReleaseAgeExcludes = ["@types/bun", "typescript"]

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true

[test]
coverage = false
onlyFailures = true
preload = ["./src/test-setup.ts"]

[test.reporter]
dots = true

